<div class="footer">
  <div class="accordionButton">
  	<img src="images/menu-button.png" width="150" height="32" />
  </div>
  <div class="accordionContent">
    <div class="accordionmain">
    <div class="menu">
   		<a href="index.php">Inicio</a> 
      <a href="who-we-are.php">Quiénes Somos</a> 
      <a href="catalog.php">Catálogo de Productos</a> 
      <a href="contact.php">Contacto</a>
    </div>
    <div class="newmenu">
    Desarrollado por <a href="http://deltatech.com.ve" target="_blank"><img src="images/deltatech_logo.png"></a>
   
 <!--Síguenos por:&nbsp;&nbsp;&nbsp;<a href="#"><img src="images/facebook.png" width="10" height="24" /></a>&nbsp;&nbsp;&nbsp;<a href="#"><img src="images/twitter.png" width="26" height="24" /></a> -->
    </div>
    </div>
  </div>